spring.application.name=bff
server.port=8080

services.appointments.base-url=${APPOINTMENTS_SERVICE_URL:http://localhost:8081}
services.catalog.base-url=${CATALOG_SERVICE_URL:http://localhost:8082}
services.audit.base-url=${AUDIT_SERVICE_URL:http://localhost:8084}
services.report.base-url=${REPORT_SERVICE_URL:http://localhost:8085}

azure.tenant-id=${AZURE_TENANT_ID:b19dac1c-44c9-4e15-9214-59ae9f63b92e}
azure.api-client-id=${AZURE_API_CLIENT_ID:6a867a28-0b42-4528-ab92-b7824aa877b3}
spring.security.oauth2.resourceserver.jwt.issuer-uri=https://login.microsoftonline.com/${azure.tenant-id}/v2.0